name: GitHub Pages

on:
  push:
    branches:
      - master  # 或者你想要发布书籍的分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Git
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
        
    - name: Build Jupyter Book
      run: |
        jupyter-book build .
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./_build/html